name: EstudoLinguagem
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.1'


dependencies:
  path: ^1.8.0
  meta: ^1.4.0

dev_dependencies:
  pedantic: ^1.11.0
